version: '3.8'
services:
  app:
    build:
      context: .
    container_name: nestjs-app
    ports:
      - '5432:5432'
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: pricing_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: pricing_system
